__author__ = 'roland'

IDMAP = {
    "rp-rtyp-code": "/_/_/_/normal",
    "rp-rtyp-idt": "/_/_/_/normal",
    "rp-rtyp-idttoken": "/_/_/_/normal",
    # "rp-selfissued": "",
    "rp-rmod-form": "/_/_/_/normal",
    "rp-idt-iss": "/_/_/issi/normal",
    "rp-idt-sub": "/_/_/itsub/normal",
    "rp-idt-aud": "/_/_/aud/normal",
    "rp-idt-iat": "/_/_/iat/normal",
    "rp-idt-kid-absent": "/_/_/nokid1jwks/normal",
    "rp-idt-kid": "/_/_/nokidjwks/normal",
    "rp-idt-at_hash": "/_/_/ath/normal",
    "rp-idt-c_hash": "/_/_/ath/normal",
    # "rp-idt-epk": "",
    "rp-alg-rs256": "/RS256/_/idts/normal",
    "rp-alg-none": "/none/_/_/normal",
    "rp-alg-hs256": "/HS256/_/idts/normal",
    "rp-alg-es256": "/ES256/_/_/normal",
    "rp-idt-signenc": "/_/_/_/normal",
    "rp-ui-hdr": "/_/_/_/normal",
    "rp-ui-body": "/_/_/_/normal",
    "rp-ui-not-query": "/_/_/_/normal",
    "rp-bad-userinfo-sub": "/_/_/uisub/normal",
    "rp-ui-sign": "/_/_/_/normal",
    "rp-ui-enc": "/_/_/_/normal",
    "rp-ui-signenc": "/_/_/_/normal",
    "rp-nonce-nocode": "/_/_/_/normal",
    "rp-nonce-invalid": "/_/_/_/nonce/normal",
    "rp-scope-openid": "/_/_/_/normal",
    "rp-scope": "/_/_/_/normal",
    "rp-tok-csbasic": "/_/_/_/normal",
    "rp-tok-cspost": "/_/_/_/normal",
    "rp-tok-pkjwt": "/_/_/_/normal",
    "rp-tok-csjwt": "/_/_/_/normal",
    "rp-webfinger": "",
    "rp-ids-email": "",
    "rp-ids-url": "",
    "rp-config": "/_/_/_/normal",
    "rp-bad-disc-issuer": "/_/_/isso/normal",
    "rp-bad-iss-issuer": "/_/_/issi/normal",
    "rp-keys-jwks_uri": "/_/_/_/normal",
    "rp-registration": "/_/_/_/normal",
    "rp-roll-op-sig": "/_/_/rotsig/normal",
    "rp-roll-rp-sig": "/_/_/_/normal",
    "rp-roll-op-enc": "/_/_/rotenc/normal",
    "rp-roll-rp-enc": "/_/_/_/normal",
    "rp-ruri-uns": "/_/_/_/normal",
    "rp-ruri-sig": "/_/_/_/normal",
    "rp-ruri-enc": "/_/_/_/normal",
    "r  p-ruri-sigenc": "/_/_/_/normal",
    "rp-reqobj": "/_/_/_/normal",
    "rp-clm-idt": "/_/_/_/normal",
    # "rp-3rd-login": "",
    "rp-clm-aggreg": "/_/_/_/_/aggregate",
    "rp-clm-dist": "/_/_/_/_/distributed"
    # "rp-logout-init": "",
    # "rp-logout-received": "",
    # "rp-change-received": ""
}